from fastapi import APIRouter, Depends, HTTPException, Path, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.logger import get_logger
from app.schemas.crop import (
    CropResponse,
    CropListResponse,
    CropResponseLite,
    CropRecommendationResponse,
)
from app.schemas.system import ErrorResponse
from app.services.crop_catalog import CropCatalog
from app.services.llm_service import get_llm_service, log_llm_generation, PROMPT_SCHEMA_VERSION
from app.services.municipality_catalog import MunicipalityCatalog
from app.services.prediction_service import PredictionService

router = APIRouter(prefix="/crops", tags=["crops"])
catalog = CropCatalog()
municipality_catalog = MunicipalityCatalog()
prediction_service = PredictionService()
llm_service = get_llm_service()
logger = get_logger("app.routers.crops")


@router.get(
    "",
    response_model=CropListResponse,
    summary="List full crop catalog",
    description=(
        "Returns all ML-supported crops with full agronomic details.\n\n"
        "Use cases:\n"
        "- Detailed crop profile pages.\n"
        "- Inputs for recommendation and planning interfaces."
    ),
)
def get_crops(db: Session = Depends(get_db)):
    logger.info("[endpoint] GET /crops called")
    logger.debug("[endpoint] Querying database for all crops")
    crops = catalog.get_all_crops(db)
    logger.info("[endpoint] GET /crops returning %s crops", len(crops))
    return CropListResponse(crops=crops, count=len(crops))


@router.get(
    "/lite",
    response_model=list[CropResponseLite],
    summary="List lite crop cards",
    description=(
        "Returns lightweight crop entries intended for quick lists/cards.\n\n"
        "Use cases:\n"
        "- Fast-loading crop pickers.\n"
        "- Recommendation side panels with minimal payload."
    ),
)
def get_crops_lite(db: Session = Depends(get_db)):
    logger.info("[endpoint] GET /crops/lite called")
    logger.debug("[endpoint] Querying database for lite crop list")
    crops = catalog.get_crops_lite(db)
    logger.info("[endpoint] GET /crops/lite returning %s crops", len(crops))
    return crops


@router.get(
    "/{crop_id}",
    response_model=CropResponse,
    summary="Get crop by ID",
    description=(
        "Returns one crop with all agronomic fields and guidance text.\n\n"
        "Use cases:\n"
        "- Fetch details for a selected crop.\n"
        "- Validate a crop identifier before prediction workflows."
    ),
    responses={
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "Crop ID does not exist in catalog.",
        }
    },
)
def get_crop(
    crop_id: str = Path(..., description="Crop identifier (e.g. aguacate, pina)"),
    db: Session = Depends(get_db),
):
    logger.info("[endpoint] GET /crops/{crop_id} called (crop_id=%s)", crop_id)
    logger.debug("[endpoint] Querying database for crop_id=%s", crop_id)
    crop = catalog.get_crop_by_id(db, crop_id)
    if not crop:
        logger.warning("[endpoint] Crop not found: %s", crop_id)
        raise HTTPException(status_code=404, detail="Crop not found")
    logger.info("[endpoint] GET /crops/{crop_id} returning crop_id=%s", crop_id)
    return crop


@router.get(
    "/{crop_id}/recommendations/{municipality_id}",
    response_model=CropRecommendationResponse,
    summary="Get practical recommendation for a crop in a municipality",
    description=(
        "Returns a short, plain-language recommendation for farmers who want to grow "
        "a specific crop in a specific municipality. The response is generated by an LLM "
        "using FAO/EcoCrop crop data, long-term climate and soil profiles, current weather, "
        "and forecast data for the region."
    ),
    responses={
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "Crop or municipality ID not found.",
        },
    },
)
def get_crop_recommendation(
    crop_id: str = Path(..., description="Crop identifier"),
    municipality_id: str = Path(..., description="Municipality DANE code (5 digits)"),
    db: Session = Depends(get_db),
):
    logger.info(
        "[endpoint] GET /crops/{crop_id}/recommendations/{municipality_id} called (crop_id=%s, municipality_id=%s)",
        crop_id,
        municipality_id,
    )

    crop = catalog.get_crop_model_by_id(db, crop_id)
    if not crop:
        logger.warning("[endpoint] Crop not found: %s", crop_id)
        raise HTTPException(status_code=404, detail="Crop not found")

    municipality = municipality_catalog.get_municipality_by_id(db, municipality_id)
    if not municipality:
        logger.warning("[endpoint] Municipality not found: %s", municipality_id)
        raise HTTPException(status_code=404, detail="Municipality not found")

    context = prediction_service.get_crop_recommendation_context(
        db,
        crop_id=crop_id,
        municipality_id=municipality_id,
    )
    if not context:
        logger.error("[endpoint] Could not build recommendation context")
        raise HTTPException(status_code=500, detail="Could not build recommendation context")

    llm_result = llm_service.generate_crop_recommendation(
        crop=context["crop"],
        municipality=context["municipality"],
        climate_summary=context["climate_summary"],
        soil_summary=context["soil_summary"],
    )

    tokens_in = llm_result.get("tokens_in")
    tokens_out = llm_result.get("tokens_out")
    tokens_total = None
    if tokens_in is not None and tokens_out is not None:
        tokens_total = tokens_in + tokens_out

    log_id = log_llm_generation(
        db,
        provider=llm_result.get("provider"),
        model=llm_result.get("model"),
        prompt_schema_version=PROMPT_SCHEMA_VERSION,
        context_summary=f"crop_recommendation:{crop_id}:{municipality_id}",
        response_json={"text": llm_result.get("text")},
        tokens_in=tokens_in,
        tokens_out=tokens_out,
        latency_ms=llm_result.get("latency_ms"),
        status=llm_result.get("status", "llm_unavailable"),
        error_message=llm_result.get("error"),
    )
    logger.debug("[endpoint] LLM generation logged id=%s", log_id)

    return CropRecommendationResponse(
        crop_id=crop_id,
        crop_name=crop.name,
        municipality_id=municipality_id,
        municipality_name=municipality.name,
        text=llm_result.get("text", ""),
        provider=llm_result.get("provider"),
        model=llm_result.get("model"),
        tokens_in=tokens_in,
        tokens_out=tokens_out,
        tokens_total=tokens_total,
        latency_ms=llm_result.get("latency_ms"),
        status=llm_result.get("status", "llm_unavailable"),
        error=llm_result.get("error"),
    )
