from fastapi import APIRouter, Depends, HTTPException, Path, Request, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.logger import get_logger
from app.schemas.crop import (
    CropResponse,
    CropListResponse,
    CropResponseLite,
    CropRecommendationResponse,
    CropNationalGuideResponse,
)
from app.schemas.system import ErrorResponse
from app.services.crop_catalog import CropCatalog
from app.services.crop_national_guide_service import get_crop_national_guide_service
from app.services.crop_recommendation_service import get_crop_recommendation_cache_service
from app.services.llm_service import get_llm_service
from app.services.municipality_catalog import MunicipalityCatalog
from app.services.prediction_service import PredictionService
from app.middleware.rate_limit import ML_LLM_GROUP, enforce_rate_limit, rate_limit

router = APIRouter(prefix="/crops", tags=["crops"])
catalog = CropCatalog()
municipality_catalog = MunicipalityCatalog()
prediction_service = PredictionService()
llm_service = get_llm_service()
guide_service = get_crop_national_guide_service()
recommendation_service = get_crop_recommendation_cache_service()
logger = get_logger("app.routers.crops")


@router.get(
    "",
    response_model=CropListResponse,
    summary="List full crop catalog",
    description=(
        "Returns all ML-supported crops with full agronomic details.\n\n"
        "Use cases:\n"
        "- Detailed crop profile pages.\n"
        "- Inputs for recommendation and planning interfaces."
    ),
)
def get_crops(db: Session = Depends(get_db)):
    logger.info("[endpoint] GET /crops called")
    logger.debug("[endpoint] Querying database for all crops")
    crops = catalog.get_all_crops(db)
    logger.info("[endpoint] GET /crops returning %s crops", len(crops))
    return CropListResponse(crops=crops, count=len(crops))


@router.get(
    "/lite",
    response_model=list[CropResponseLite],
    summary="List lite crop cards",
    description=(
        "Returns lightweight crop entries intended for quick lists/cards.\n\n"
        "Use cases:\n"
        "- Fast-loading crop pickers.\n"
        "- Recommendation side panels with minimal payload."
    ),
)
def get_crops_lite(db: Session = Depends(get_db)):
    logger.info("[endpoint] GET /crops/lite called")
    logger.debug("[endpoint] Querying database for lite crop list")
    crops = catalog.get_crops_lite(db)
    logger.info("[endpoint] GET /crops/lite returning %s crops", len(crops))
    return crops


@router.get(
    "/{crop_id}",
    response_model=CropResponse,
    summary="Get crop by ID",
    description=(
        "Returns one crop with all agronomic fields and guidance text.\n\n"
        "Use cases:\n"
        "- Fetch details for a selected crop.\n"
        "- Validate a crop identifier before prediction workflows."
    ),
    responses={
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "Crop ID does not exist in catalog.",
        }
    },
)
def get_crop(
    crop_id: str = Path(..., description="Crop identifier (e.g. aguacate, pina)"),
    db: Session = Depends(get_db),
):
    logger.info("[endpoint] GET /crops/{crop_id} called (crop_id=%s)", crop_id)
    logger.debug("[endpoint] Querying database for crop_id=%s", crop_id)
    crop = catalog.get_crop_by_id(db, crop_id)
    if not crop:
        logger.warning("[endpoint] Crop not found: %s", crop_id)
        raise HTTPException(status_code=404, detail="Crop not found")
    logger.info("[endpoint] GET /crops/{crop_id} returning crop_id=%s", crop_id)
    return crop


@router.get(
    "/{crop_id}/recommendations/{municipality_id}",
    response_model=CropRecommendationResponse,
    summary="Get practical recommendation for a crop in a municipality",
    description=(
        "Returns a short, plain-language recommendation for farmers who want to grow "
        "a specific crop in a specific municipality. The response is generated by an LLM "
        "using FAO/EcoCrop crop data, long-term climate and soil profiles, current weather, "
        "and forecast data for the region."
    ),
    responses={
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "Crop or municipality ID not found.",
        },
    },
)
@enforce_rate_limit
@rate_limit(ML_LLM_GROUP)
def get_crop_recommendation(
    http_request: Request,
    crop_id: str = Path(..., description="Crop identifier"),
    municipality_id: str = Path(..., description="Municipality DANE code (5 digits)"),
    db: Session = Depends(get_db),
):
    logger.info(
        "[endpoint] GET /crops/{crop_id}/recommendations/{municipality_id} called (crop_id=%s, municipality_id=%s)",
        crop_id,
        municipality_id,
    )

    crop = catalog.get_crop_model_by_id(db, crop_id)
    if not crop:
        logger.warning("[endpoint] Crop not found: %s", crop_id)
        raise HTTPException(status_code=404, detail="Crop not found")

    municipality = municipality_catalog.get_municipality_by_id(db, municipality_id)
    if not municipality:
        logger.warning("[endpoint] Municipality not found: %s", municipality_id)
        raise HTTPException(status_code=404, detail="Municipality not found")

    recommendation = recommendation_service.get_or_generate(
        db=db,
        crop=crop,
        municipality=municipality,
    )

    logger.info(
        "[endpoint] GET /crops/{crop_id}/recommendations/{municipality_id} returning recommendation for crop_id=%s municipality_id=%s cached=%s",
        crop_id,
        municipality_id,
        recommendation.get("cached"),
    )
    return CropRecommendationResponse(**recommendation)


@router.get(
    "/{crop_id}/national-guide",
    response_model=CropNationalGuideResponse,
    summary="Get national farmer guide for a crop",
    description=(
        "Returns a farmer-friendly national guide for a crop. The guide covers "
        "planting, harvest, basic techniques, seasons, common pests and important "
        "warnings. It is generated with an LLM and cached for 3 months."
    ),
    responses={
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "Crop ID does not exist in catalog.",
        },
    },
)
@enforce_rate_limit
@rate_limit(ML_LLM_GROUP)
def get_crop_national_guide(
    http_request: Request,
    crop_id: str = Path(..., description="Crop identifier (e.g. aguacate, cebolla)"),
    db: Session = Depends(get_db),
):
    logger.info("[endpoint] GET /crops/{crop_id}/national-guide called (crop_id=%s)", crop_id)
    crop = catalog.get_crop_model_by_id(db, crop_id)
    if not crop:
        logger.warning("[endpoint] Crop not found: %s", crop_id)
        raise HTTPException(status_code=404, detail="Crop not found")

    guide = guide_service.get_or_generate(db=db, crop=crop)
    logger.info("[endpoint] GET /crops/{crop_id}/national-guide returning guide for crop_id=%s", crop_id)
    return CropNationalGuideResponse(**guide)
